# Generated by Django 4.2.13 on 2024-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBikeCarapp', '0004_bike_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('standard', 'standard'), ('cruiser', 'cruiser'), ('touring', 'touring'), ('sports', 'sports'), ('scooters ', 'scooters ')], max_length=200),
        ),
    ]
