# Generated by Django 4.2.13 on 2024-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBikeCarapp', '0005_alter_bike_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='location_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='original_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('sports', 'Sports'), ('scooters', 'Scooters')], max_length=200),
        ),
    ]
