# Generated by Django 4.2.13 on 2024-07-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentBikeCarapp', '0006_bike_deposit_bike_location_bike_location_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='category',
        ),
    ]
