# Generated by Django 4.2.13 on 2024-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBikeCarapp', '0007_remove_bike_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard'), ('cruiser', 'Cruiser'), ('touring', 'Touring'), ('sports', 'Sports'), ('scooters', 'Scooters')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
