# Generated by Django 4.2.13 on 2024-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBikeCarapp', '0010_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
